/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cap8_1;

import javax.swing.*;
/**
 *
 * @author anatol
 */
public class MatrixJFrame extends javax.swing.JFrame {

    JPanel jPanelV;
    /**
     * Creates new form MatrixJFrame
     */
    public MatrixJFrame() {
        initComponents();
/*        jPanelV=new JPanel();
        //jPanelV.setBounds(WIDTH, WIDTH, WIDTH, HEIGHT);
        JLabel jLabelV=new JLabel("Matrix");
        jPanelV.add(jLabelV);
        this.add(jPanelV);
        getContentPane().add(jPanelV);
        jPanelV.setVisible(true);
 */   }
    
    public void OppenFrame(){
        JLabel jLabelV=new JLabel("Matrix");
        getContentPane().add(jLabelV);
        jLabelV.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Creat Matrix");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanelV=new JPanel();
        //jPanelV.setBounds(WIDTH, WIDTH, WIDTH, HEIGHT);
        JLabel jLabelV=new JLabel("Matrix");
        jPanelV.add(jLabelV);
        this.add(jPanelV);
        getContentPane().add(jPanelV);
        jPanelV.update(jPanelV.getGraphics());
        //jLabelV.
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
